Precompiled runtime (#21)
* Use pre-compiled runtime archive by default

* 🚨 Switch prefix from `/app/.heroku` to `/app/kong-runtime`

* 🐞

* Fix bad Kong PATH entries. Add backward-compat prefix link.

* Correct S3 URL for pre-compiled Kong

* Correct context for pre-compiled Kong

* 📚 buildpack dev notes

* Support custom runtime archive URL and docs

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -18,7 +18,8 @@ BP_DIR=`cd $(dirname $0); cd ..; pwd`
 VENDOR_DIR=${BP_DIR}/vendor
 
 # Make dyno runtime-compatible prefix for compiled artifacts
-APP_PREFIX=/app/.heroku
+KONG_RUNTIME=kong-runtime
+APP_PREFIX=/app/$KONG_RUNTIME
 mkdir -p $APP_PREFIX
 
 # Cache compilation artifacts between builds
@@ -26,16 +27,21 @@ BP_CACHE_DIR="$CACHE_DIR/heroku-kong-buildpack"
 mkdir -p $BP_CACHE_DIR
 PREFIX_CACHE_DIR=$BP_CACHE_DIR/app_prefix
 
+IS_CUSTOM_BUILD=false
+RUNTIME_ARCHIVE_URL="${KONG_RUNTIME_ARCHIVE_URL:-https://s3-us-west-1.amazonaws.com/kong-on-heroku/kong-runtime-v6.0.0.tgz}"
+
 # Source for Kong
 if [ -f "${ENV_DIR}/KONG_GIT_URL" ]
 then
+  IS_CUSTOM_BUILD=true
   KONG_GIT_URL=`cat ${ENV_DIR}/KONG_GIT_URL`
 else
-  KONG_GIT_URL="https://github.com/Mashape/kong.git"
+  KONG_GIT_URL="https://github.com/kong/kong.git"
 fi
 # commit or tag to checkout
 if [ -f "${ENV_DIR}/KONG_GIT_COMMITISH" ]
 then
+  IS_CUSTOM_BUILD=true
   KONG_GIT_COMMITISH=`cat ${ENV_DIR}/KONG_GIT_COMMITISH`
 else
   KONG_GIT_COMMITISH="0.14.1"
@@ -101,18 +107,20 @@ done
 
 topic "Writing profile script"
 mkdir -p $BUILD_DIR/.profile.d
+# ~~~~~ Keep these values in sync with the build-time exports below ~~~~~
 cat <<EOF >$BUILD_DIR/.profile.d/000_buildpack_kong.sh
-export PATH="\$HOME/.heroku/nginx/sbin:\$HOME/.heroku/luajit/bin:\$HOME/.heroku/bin:\$HOME/.apt/usr/local/bin:\$HOME/.apt/usr/bin:\$HOME/.apt/usr/sbin:\$PATH"
-export LD_LIBRARY_PATH="\$HOME/.heroku/lib:\$HOME/.apt/usr/lib/x86_64-linux-gnu:\$HOME/.apt/usr/local/lib:\$HOME/.apt/usr/lib:/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib:\$LD_LIBRARY_PATH"
-export LIBRARY_PATH="\$HOME/.heroku/lib:\$HOME/.apt/usr/lib/x86_64-linux-gnu:\$HOME/.apt/usr/local/lib:\$HOME/.apt/usr/lib:/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib:\$LIBRARY_PATH"
-export INCLUDE_PATH="\$HOME/.heroku/include:\$HOME/.apt/usr/local/include:\$HOME/.apt/usr/include:/usr/include/x86_64-linux-gnu:/usr/include:\$INCLUDE_PATH"
+export PATH="\$HOME/${KONG_RUNTIME}/nginx/sbin:\$HOME/${KONG_RUNTIME}/luajit/bin:\$HOME/${KONG_RUNTIME}/bin:\$HOME/.apt/usr/local/bin:\$HOME/.apt/usr/bin:\$HOME/.apt/usr/sbin:\$PATH"
+export LD_LIBRARY_PATH="\$HOME/${KONG_RUNTIME}/lib:\$HOME/.apt/usr/lib/x86_64-linux-gnu:\$HOME/.apt/usr/local/lib:\$HOME/.apt/usr/lib:/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib:\$LD_LIBRARY_PATH"
+export LIBRARY_PATH="\$HOME/${KONG_RUNTIME}/lib:\$HOME/.apt/usr/lib/x86_64-linux-gnu:\$HOME/.apt/usr/local/lib:\$HOME/.apt/usr/lib:/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib:\$LIBRARY_PATH"
+export INCLUDE_PATH="\$HOME/${KONG_RUNTIME}/include:\$HOME/.apt/usr/local/include:\$HOME/.apt/usr/include:/usr/include/x86_64-linux-gnu:/usr/include:\$INCLUDE_PATH"
 export CPATH="\$INCLUDE_PATH"
 export CPPPATH="\$INCLUDE_PATH"
 export PKG_CONFIG_PATH="\$HOME/.apt/usr/local/lib/pkgconfig:\$HOME/.apt/usr/lib/x86_64-linux-gnu/pkgconfig:\$HOME/.apt/usr/lib/pkgconfig:\$PKG_CONFIG_PATH"
-export LUA_PATH="\$HOME/lib/?.lua;\$HOME/lib/?/init.lua;\$HOME/.luarocks/share/lua/5.1/?.lua;\$HOME/.luarocks/share/lua/5.1/?/init.lua;\$HOME/.heroku/share/lua/5.1/?.lua;\$HOME/.heroku/share/lua/5.1/?/init.lua;./?.lua"
-export LUA_CPATH="\$HOME/lib/?.so;\$HOME/.luarocks/lib/lua/5.1/?.so;\$HOME/.heroku/lib/lua/5.1/?.so;./?.so"
+export LUA_PATH="\$HOME/lib/?.lua;\$HOME/lib/?/init.lua;\$HOME/.luarocks/share/lua/5.1/?.lua;\$HOME/.luarocks/share/lua/5.1/?/init.lua;\$HOME/${KONG_RUNTIME}/share/lua/5.1/?.lua;\$HOME/${KONG_RUNTIME}/share/lua/5.1/?/init.lua;./?.lua"
+export LUA_CPATH="\$HOME/lib/?.so;\$HOME/.luarocks/lib/lua/5.1/?.so;\$HOME/${KONG_RUNTIME}/lib/lua/5.1/?.so;./?.so"
 EOF
 
+# ~~~~~ Keep these values in sync with the runtime profile script above ~~~~~
 export PATH="$APP_PREFIX/nginx/sbin:$APP_PREFIX/luajit/bin:$APP_PREFIX/bin:$BUILD_DIR/.apt/usr/local/bin:$BUILD_DIR/.apt/usr/bin:$BUILD_DIR/.apt/usr/sbin:/sbin:$PATH"
 export LD_LIBRARY_PATH="$APP_PREFIX/lib:$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu:$BUILD_DIR/.apt/usr/local/lib:$BUILD_DIR/.apt/usr/lib:/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib"
 export LIBRARY_PATH="$APP_PREFIX/lib:$BUILD_DIR/.apt/usr/lib/x86_64-linux-gnu:$BUILD_DIR/.apt/usr/local/lib:$BUILD_DIR/.apt/usr/lib:/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu:/usr/lib"
@@ -126,114 +134,121 @@ export LUA_CPATH="$BUILD_DIR/lib/?.so;$BUILD_DIR/.luarocks/lib/lua/5.1/?.so;$APP
 #give environment to later buildpacks
 export | grep -E -e ' (PATH|LD_LIBRARY_PATH|LIBRARY_PATH|INCLUDE_PATH|CPATH|CPPPATH|PKG_CONFIG_PATH)='  > "$BP_DIR/export"
 
-# Once the installed packages are in the PATH, use them.
-
-# Build from source to have dyno-compatible path prefix
-
-# Cache the build
-VENDOR_CACHE_DIR=${BP_CACHE_DIR}/vendor
-mkdir -p ${VENDOR_CACHE_DIR}
-
-# Detect changes in the vendor/ sources
-topic "Detecting changes in vendor/"
-cd ${VENDOR_DIR}
-VENDOR_DIFF=${BP_CACHE_DIR}/.vendor-diff
-VENDOR_HASH=${BP_CACHE_DIR}/.vendor-hash
-VENDOR_HASH_NEW=${VENDOR_HASH}-new
-touch ${VENDOR_DIFF}
-touch ${VENDOR_HASH}
-touch ${VENDOR_HASH_NEW}
-openssl dgst -sha1 * > ${VENDOR_HASH_NEW}
-# `diff` signals differences with exit codes. Don't fail fast.
-set +e
-diff ${VENDOR_HASH} ${VENDOR_HASH_NEW} > ${VENDOR_DIFF}
-DIFF_STATUS=$?
-set -e
-mv -f ${VENDOR_HASH_NEW} ${VENDOR_HASH}
-
-if [ "$DIFF_STATUS" == 0 ] && [ -d "$PREFIX_CACHE_DIR" ]
+if [ $IS_CUSTOM_BUILD = false ]
 then
-  topic "Restoring from cache"
-  cp -R $PREFIX_CACHE_DIR/* $APP_PREFIX/
-
-elif [ "$DIFF_STATUS" == 0 ] || [ "$DIFF_STATUS" == 1 ]
-then
-  topic "Changes detected"
-  IFS=$'\n' 
-  for DIFF_LINE in $(cat "$VENDOR_DIFF"); do
-    echo "       $DIFF_LINE"
-  done
-  unset IFS
-
-  # Clean-up previous cache
-  rm ${VENDOR_DIFF}
-  rm -rf ${VENDOR_CACHE_DIR}
-  # and cache the new source code
-  mv ${VENDOR_DIR} ${VENDOR_CACHE_DIR}
-  cd ${VENDOR_CACHE_DIR}
-
-  topic "Building OpenSSL"
-  openssl_name="openssl-${OPENSSL_VERSION}"
-  mkdir -p "${openssl_name}"
-  tar -xz -f "${openssl_name}.tar.gz" -C "${openssl_name}" --strip-components=1
-  cd "${openssl_name}"
-  ./config --prefix=$APP_PREFIX -fPIC
-  make
-  make install
-  cd ..
-
-  topic "Building OpenResty"
-  tar -xf openresty-${OPENRESTY_VERSION}.tar.gz
-  cd openresty-${OPENRESTY_VERSION}
-  ./configure --prefix=$APP_PREFIX --with-pcre-jit --with-ipv6 --with-http_realip_module --with-http_ssl_module --with-http_stub_status_module --with-http_v2_module --with-openssl=${VENDOR_CACHE_DIR}/openssl-${OPENSSL_VERSION}
-  make
-  make install
-  cd ..
-
-
-  topic "Building LuaRocks"
-  tar -xf luarocks-${LUAROCKS_VERSION}.tar.gz
-  cd luarocks-${LUAROCKS_VERSION}
-  ./configure --prefix=${APP_PREFIX} --lua-suffix=jit --with-lua=${APP_PREFIX}/luajit --with-lua-include=${APP_PREFIX}/luajit/include/luajit-2.1
-  make build
-  make install
-  cd ..  
-
-
-  topic "Caching build"
-  mkdir -p $PREFIX_CACHE_DIR
-  cp -Rf $APP_PREFIX/* $PREFIX_CACHE_DIR/
-
+  topic "Installing Kong for buildpack from ${RUNTIME_ARCHIVE_URL}"
+  curl --silent --location "${RUNTIME_ARCHIVE_URL}" | tar xzm -C "${APP_PREFIX}" --strip-components=2
 else
-  error "Error detecting cached build: diff exited ${DIFF_STATUS}"
-fi
 
-topic "Building Kong from ${KONG_GIT_URL}#${KONG_GIT_COMMITISH}"
-# Move the unfortunately named `.luarocks` spec file so that it doesn't
-# interfere during CI. We're migrating Kong apps to use `Rockfile` instead.
-if [ -f "$BUILD_DIR/.luarocks" ]; then
-  mv "$BUILD_DIR/.luarocks" "$BUILD_DIR/Rockfile"
+  # Proceed with build from source
+  # Build from source to have dyno-compatible path prefix
+
+  # Cache the build
+  VENDOR_CACHE_DIR=${BP_CACHE_DIR}/vendor
+  mkdir -p ${VENDOR_CACHE_DIR}
+
+  # Detect changes in the vendor/ sources
+  topic "Detecting changes in vendor/"
+  cd ${VENDOR_DIR}
+  VENDOR_DIFF=${BP_CACHE_DIR}/.vendor-diff
+  VENDOR_HASH=${BP_CACHE_DIR}/.vendor-hash
+  VENDOR_HASH_NEW=${VENDOR_HASH}-new
+  touch ${VENDOR_DIFF}
+  touch ${VENDOR_HASH}
+  touch ${VENDOR_HASH_NEW}
+  openssl dgst -sha1 * > ${VENDOR_HASH_NEW}
+  # `diff` signals differences with exit codes. Don't fail fast.
+  set +e
+  diff ${VENDOR_HASH} ${VENDOR_HASH_NEW} > ${VENDOR_DIFF}
+  DIFF_STATUS=$?
+  set -e
+  mv -f ${VENDOR_HASH_NEW} ${VENDOR_HASH}
+
+  if [ "$DIFF_STATUS" == 0 ] && [ -d "$PREFIX_CACHE_DIR" ]
+  then
+    topic "Restoring from cache"
+    cp -R $PREFIX_CACHE_DIR/* $APP_PREFIX/
+
+  elif [ "$DIFF_STATUS" == 0 ] || [ "$DIFF_STATUS" == 1 ]
+  then
+    topic "Changes detected"
+    IFS=$'\n' 
+    for DIFF_LINE in $(cat "$VENDOR_DIFF"); do
+      echo "       $DIFF_LINE"
+    done
+    unset IFS
+
+    # Clean-up previous cache
+    rm ${VENDOR_DIFF}
+    rm -rf ${VENDOR_CACHE_DIR}
+    # and cache the new source code
+    mv ${VENDOR_DIR} ${VENDOR_CACHE_DIR}
+    cd ${VENDOR_CACHE_DIR}
+
+    topic "Building OpenSSL"
+    openssl_name="openssl-${OPENSSL_VERSION}"
+    mkdir -p "${openssl_name}"
+    tar -xz -f "${openssl_name}.tar.gz" -C "${openssl_name}" --strip-components=1
+    cd "${openssl_name}"
+    ./config --prefix=$APP_PREFIX -fPIC
+    make
+    make install
+    cd ..
+
+    topic "Building OpenResty"
+    tar -xf openresty-${OPENRESTY_VERSION}.tar.gz
+    cd openresty-${OPENRESTY_VERSION}
+    ./configure --prefix=$APP_PREFIX --with-pcre-jit --with-ipv6 --with-http_realip_module --with-http_ssl_module --with-http_stub_status_module --with-http_v2_module --with-openssl=${VENDOR_CACHE_DIR}/openssl-${OPENSSL_VERSION}
+    make
+    make install
+    cd ..
+
+
+    topic "Building LuaRocks"
+    tar -xf luarocks-${LUAROCKS_VERSION}.tar.gz
+    cd luarocks-${LUAROCKS_VERSION}
+    ./configure --prefix=${APP_PREFIX} --lua-suffix=jit --with-lua=${APP_PREFIX}/luajit --with-lua-include=${APP_PREFIX}/luajit/include/luajit-2.1
+    make build
+    make install
+    cd ..  
+
+
+    topic "Caching build"
+    mkdir -p $PREFIX_CACHE_DIR
+    cp -Rf $APP_PREFIX/* $PREFIX_CACHE_DIR/
+
+  else
+    error "Error detecting cached build: diff exited ${DIFF_STATUS}"
+  fi
+
+  topic "Building Kong from ${KONG_GIT_URL}#${KONG_GIT_COMMITISH}"
+  # Move the unfortunately named `.luarocks` spec file so that it doesn't
+  # interfere during CI. We're migrating Kong apps to use `Rockfile` instead.
+  if [ -f "$BUILD_DIR/.luarocks" ]; then
+    mv "$BUILD_DIR/.luarocks" "$BUILD_DIR/Rockfile"
+  fi
+  # Ensure we don't have Kong from a previous build
+  luarocks remove kong || true
+  if [ -d "$KONG_SOURCE_DIR" ]
+  then
+    cd $KONG_SOURCE_DIR
+    git fetch
+    git fetch --tags
+    git reset --hard $(git rev-list -n 1 $KONG_GIT_COMMITISH)
+  else
+    git clone $KONG_GIT_URL $KONG_SOURCE_DIR
+    cd $KONG_SOURCE_DIR
+    git checkout $KONG_GIT_COMMITISH
+  fi
+  export OPENSSL_DIR=${APP_PREFIX}
+  # Install Kong itself from the cloned git repo
+  luarocks make ./kong-*.rockspec
+  # Install Kong's dependencies via LuaRocks
+  # (`--local` is required for this to do anything)
+  luarocks install --local ./kong-*.rockspec
+  mkdir -p ${APP_PREFIX}/bin
+  mv bin/* ${APP_PREFIX}/bin/
 fi
-# Ensure we don't have Kong from a previous build
-luarocks remove kong || true
-if [ -d "$KONG_SOURCE_DIR" ]
-then
-  cd $KONG_SOURCE_DIR
-  git fetch
-  git fetch --tags
-  git reset --hard $(git rev-list -n 1 $KONG_GIT_COMMITISH)
-else
-  git clone $KONG_GIT_URL $KONG_SOURCE_DIR
-  cd $KONG_SOURCE_DIR
-  git checkout $KONG_GIT_COMMITISH
-fi
-export OPENSSL_DIR=${APP_PREFIX}
-# Install Kong itself from the cloned git repo
-luarocks make ./kong-*.rockspec
-# Install Kong's dependencies via LuaRocks
-# (`--local` is required for this to do anything)
-luarocks install --local ./kong-*.rockspec
-mv bin/* ${APP_PREFIX}/bin/
 
 topic "Installing Lua rocks specified in Rockfile"
 cd ${BUILD_DIR}
@@ -249,8 +264,18 @@ mv config/* $BUILD_DIR/config
 mkdir -p $BUILD_DIR/bin
 cp $BP_DIR/bin/app/heroku-* $BUILD_DIR/bin/
 
+topic "Applying buildpack v6.0.0 backward-compatibility patch"
+if [ ! -d ".heroku" ]
+then
+  echo "Linking '/app/.heroku' to '/app/$KONG_RUNTIME'" | indent
+  ln -s "$KONG_RUNTIME/" .heroku
+else
+  echo "'/app/.heroku' exists. Linking skipped." | indent
+  echo "Ensure the app's 'config/kong.conf.etlua' sets the prefix to '/app/$KONG_RUNTIME'" | indent
+fi
+
 # Avoid moving build for CI, because build is in the right place already.
 if [ ! "$BUILD_DIR" = "/app" ]; then
   topic "Making build artifacts available to app"
-  mv $APP_PREFIX $BUILD_DIR/.heroku
+  mv $APP_PREFIX $BUILD_DIR/$KONG_RUNTIME
 fi
